{{- if .Values.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      {{- if .Values.ingress.traefikMiddleware }}
      middlewares:
        - name: authelia
          namespace: authelia
      {{- end }}
      services:
        - name: {{ .Release.Name }}
          port: {{ .Values.service.port }}
  tls:
    certResolver: {{ .Values.ingress.certResolver | default "letsencrypt" }}
{{- end }}
