apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s-postgres:5432/%s" .Values.postgres.user .Values.postgres.password .Release.Name .Values.postgres.database | quote }}
  DATABASE_PROVIDER: "postgresql"
  JWT_SECRET: {{ .Values.env.JWT_SECRET | quote }}
