image:
  repository: ghcr.io/theo-mrn/trivy-dashboard-web
  tag: "latest"
  pullPolicy: Always

replicaCount: 2

ingress:
  enabled: true
  host: trivyhub.cluster.afflair.app
  traefikMiddleware: "authelia-authelia@kubernetescrd"
  certResolver: letsencrypt

env:
  JWT_SECRET: "41c6e9aa066c3806a7ea4d058c5b044c129c82d2fad9c31875910c3adf357785"

postgres:
  enabled: true
  image: postgres:16-alpine
  database: trivyhub
  user: trivyhub
  password: "2833a2857d945341ee1e306c1e8f6b2e"
  storageSize: 5Gi
  storageClass: longhorn
