image:
  repository: ghcr.io/theo-mrn/trivy-dashboard-web
  tag: "stag"
  pullPolicy: Always

replicaCount: 1

ingress:
  enabled: true
  host: stag.trivyhub.cluster.afflair.app
  traefikMiddleware: "authelia-authelia@kubernetescrd"
  certResolver: letsencrypt

env:
  JWT_SECRET: "07187d23d047e89c6f3f8085251658b6fcd5c479516191d24ae24838558f602a"

postgres:
  enabled: true
  image: postgres:16-alpine
  database: trivyhub
  user: trivyhub
  password: "d2554f948e7f4e1e60ef98bf18101cee"
  storageSize: 2Gi
  storageClass: longhorn

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
